version: '3'

services:
  mysql:
    image: mysql:8
    container_name: ${DB_CONTAINER_NAME:-mysql_app}
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    networks:
      - app-network

  fastapi:
    build:
      context: module_with_reviews_back/.
    container_name: fastapi_app
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - "8000:8000"
    restart: on-failure:10

  react:
    build:
      context: module_with_reviews_front/.
    depends_on:
      - fastapi
    networks:
      - app-network
    ports:
      - "3000:3000"
    restart: on-failure:10

networks:
  app-network:
    driver: bridge
